### ISSUE TITLE
Relaton local cache does not store "fetched" attribute

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#16]
Relaton local cache now fetches every single time because the "fetched" data element is not provided in the local cache entry. @andrew2net can you help fix this? Thanks!

**Comment by andrew2net** [comment]
Yes, the fetched element was missed in `IsoBibliographicItem.to_xml`. Fixed it. Now it needs to publish last `iso-bib-item` gem or install it locally.

**Comment by ronaldtse** [comment]
@andrew2net is this all done? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse it is fixed but I don't know if it is published. @opoudjis manages versions.

**Comment by opoudjis** [comment]
Yes, "fetched" is being retrieved, and is confirmed as retrieved in the iso-bib-item rspec. There have been three gem releases of iso-bib-item since Oct 24. Closing.
