### ISSUE TITLE
Create "relaton-nist" gem for NIST publications

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#21]
Given we have a precedent that every Metanorma gem has a Relaton equivalent, it's time for the Relaton-NIST gem.

The full list of NIST publications can be found here:
https://csrc.nist.gov/publications/

**Comment by ronaldtse** [comment]
You can look at this one:

https://csrc.nist.gov/CSRC/media/Publications/Shared/documents/NIST-Cybersecurity-Publications.xlsx

Actually these are only cybersecurity pubs. There are more NIST publications.

**Comment by ronaldtse** [comment]
Their full listing is here. 

https://www.nist.gov/publications

Perhaps we can utilize their Search function too.

**Comment by andrew2net** [comment]
@ronaldtse do we search NIST documents by Report Number?

**Comment by andrew2net** [comment]
@ronaldtse NIST documents have statuses `Draft`, `Final`, `Retired Draft`, `Withdrawn`. How should they correlate to IsoBib statuses?

**Comment by ronaldtse** [comment]
@andrew2net , I think each Relaton flavor can have its own set of statuses. This just means that for NIST publications we have `Draft`, `Final`, `Retired Draft`, `Withdrawn`.

What do you think @opoudjis ?

**Comment by opoudjis** [comment]
I would prefer we map them all to a consistent set of statuses, and I think I attempted to for one gem, but @ronaldtse is right: each standards body has its own established statuses, and the bibliographic display for those standards has to replicate them.

**Comment by opoudjis** [comment]
is this issue still open?

**Comment by andrew2net** [comment]
@opoudjis I thin we can close it.
