### ISSUE TITLE
Providing Relaton XML for ISO Geodetic Registry?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#25]
The ISO Geodetic Registry that we host has a function for showing citation information.

e.g. https://registry.isotc211.org/item/f35d0f6f-a998-4e5e-9ffb-43a96907b803

Click on "Information Source", a popup like this will appear.

<img width="909" alt="Screen Shot 2019-03-17 at 8 21 59 PM" src="https://user-images.githubusercontent.com/11865/54490648-83152f80-48f2-11e9-8de8-1d926a73933f.png">

Should we also provide the Relaton XML for it?

ping: @opoudjis

**Comment by opoudjis** [comment]
Discussed in chat; suggested value-add such as navigation to related standards or relaton website presentation, not just XML, be used to demonstrate utility of Relaton XML feed to new audience.
