### ISSUE TITLE
Make relaton flavour XML variants available to relaton

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton#35]
Manage these as another layer of includes in the RNC gramma, migrating them from metanorma-model-iso RNCs. Only concerns the bibitem element and its BibliographicItem type.

**Comment by opoudjis** [comment]
@ronaldtse I now think this is a very bad idea.

Bibliographic information occurs in two places in Metanorma: the description of the document itself, bibdata, and the description of references, bibitem.

bibdata has all sorts of standards-specific stuff, and is customised according to the needs of the standard; the latest instance of that was me shoving the idiosyncratic annotations on withdrawn documents from NIST into bibdata/note.

bibitem on the other hand is meant to take in references from any number of standards bodies, and parse them without incident. bibitem is what the relaton gem is populating, not bibdata. And bibitem should be completely generic across standards flavours. And if it isn't, well (I hate my life for saying this) then Relaton is going to have to change to make it generic. We cannot have 10 schema definitions of bibitem working at once in a bibliography. That's not how XML validation works.

I hate this project.

This means that I am going to have to go through all fucking 10 flavours of Metanorma, identify any discrepancies that impact bibitem, and get rid of them. That is a new ticket, and I may get to it in 2 months. And this ticket needs to close.

**Comment by ronaldtse** [comment]
> Relaton is going to have to change to make it generic. We cannot have 10 schema definitions of bibitem working at once in a bibliography.

That's true. I feel that XML variants should be still based on a common tag set but allow differentiation via different attributes.

However, it is necessary that bibdata and bibitem serve off an identical structure. For example, bibdata is based on the general bibitem. Point is we must allow bibdata to be converted/extracted in to bibitem.

**Comment by opoudjis** [comment]
> However, it is necessary that bibdata and bibitem serve off an identical structure. For example, bibdata is based on the general bibitem. Point is we must allow bibdata to be converted/extracted in to bibitem.

That can be done by reducing bibdata to bibitem, filtering or removing any standards-specific metadata. I think I'm agreeing with you.

So bibdata can be distinct, for reasons of presentation, but bibdata is reduced to a common bibitem representation, which is universal. And bibdata > bibitem will become functionality necessary to relaton-cli, once we know what that those discrepancies are.

**Comment by ronaldtse** [comment]
Awesome. Thanks @opoudjis .

**Comment by opoudjis** [comment]
@ronaldtse has decided that relaton needs to extract as much information as possible about bibliographic items, and not just information specific to citations.

This means that, while bibitem must if at all possible have a generic schema across all flavours, relaton will in fact be outputting a flavour-specific bibdata output.

Part of the requisite functionality for the relaton gem will be to strip out flavour-specific XML elements, for when the bibliographic item is to be used in a bibliography. @andrew2net, there will be a ticket. Eventually.

**Comment by opoudjis** [comment]
Aim is to isolate flavour-specific components in bibdata, and gather them into a single container, where feasible; that bibdata-specific data can then be stripped in relaton to generate a simple bibitem entry.

**Comment by opoudjis** [comment]
ISO restrictions:

stage =
  element stage {
    ("00" | "10" | "20" | "30" | "40" | "50" | "60" | "90" | "95" )
  }

substage =
  element substage {
    ("00" | "20" | "60" | "90" | "92" | "93" | "98" | "99" )
  }

iteration =
  element iteration { xsd:int }

**Comment by opoudjis** [comment]
Creating in-code validation for attributes no longer validated by grammar.
