### ISSUE TITLE
Develop and provide BibTeX to Relaton model mapping

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#37]
From #32 @opoudjis 

> This will involve a mapping of bibtex into relaton, which I will provide.

You can refer to the `bibutils` package (http://bibutils.refbase.org/bibutils.html) 

And BibTeX keys are described here: https://www1.citavi.com/sub/manual6/en/index.html?importing_a_bibtex_file.html

**Comment by opoudjis** [comment]
... Why is this high priority?

Seriously, why?

**Comment by ronaldtse** [comment]
Because we need to support BibTeX import to relaton, and it is easy for you.

**Comment by opoudjis** [comment]
I will do mappings, for three different reference systems (because maintaining feasible scope in software projects is such a quaint notion), when the relaton model stabilises. 

The other two tickets mention writing import and export filters. I will write no such thing for bibtex, so you will need to write that ticket and assign it to someone else.

**Comment by opoudjis** [comment]
This mapping is one-way. BibTeX => Relaton.

# entry type

entry type => bibitem/@type: most types are the same; `mastersthesis`, `phdthesis` => `thesis`, `conference` => `inproceedings` (it is an alias within BibTeX)

# Author

BibTeX processes names as follows:

````
author :=  authorName ("and" authorName)*
authorName := Surname, Forename MiddleName* | Forename MiddleName* Surname
Surname := \s+ | "{" [^}]+ "}"
Forename := \s+ | "{" [^}]+ "}"
MiddleName := \s+ | "{" [^}]+ "}"
````

These map as:

authorName => contributor[role/@type = "author"]
surname => contributor/name/surname
forename => contributor/name/forename
middlename => contributor/name/forename

**Comment by opoudjis** [comment]
You've pointed me to bibutils; ... this is 12 year old C code with almost no documentation, so it isn't that useful as a reference. Did you want to use MODS XML somehow? That doesn't seem that useful to me either.

**Comment by opoudjis** [comment]
Inasmuch as I was only asked for a mapping, I believe this ticket is done.

**Comment by opoudjis** [comment]
... Actually, is the mapping meant to be bidirectional, @ronaldtse? Given the narrow scope of BibTeX, I'm not sure I need to say a lot more, but there is no bibtex type corresponding to standard for example, you would have to use techreport.

**Comment by ronaldtse** [comment]
@opoudjis yes, the mapping is meant to be bidirectional, but not supposed to support full roundtripping.

i.e. in Relaton we should be able to import BibTeX, and we should also be able to export BibTeX.

In other words, we will need to implement these methods:
* `relaton_object.to_bibtex`
* `Relaton.from_bibtex(bibtex)`

**Comment by andrew2net** [comment]
> type => classification[@type = "type"]

> keywords => classification[@type = "keyword"] (We do have keywords in bibdata but not bibitem; am not convinced they are needed in bibitem. If you think so, we have to move them now.)

> mendeley-tags => classification[@type = "mendeley"]

@opoudjis Bibitem grammar allows only one `classification` element. Are the `type`, `keywords`, and `mendeley-tags` mutual excluded?

**Comment by opoudjis** [comment]
Crap. They are not, and a single classification element is indefensible anyway if classifications are typed. Will update grammar. Sorry.

**Comment by andrew2net** [comment]
> institution => contributor[role/@type = "sponsor"]/organization/name (does not coocur with school)

> organization => contributor[role/@type = "sponsor"]/organization/name (does not coccur with institution or school)

> school => contributor[role/@type = "sponsor"]/organization/name

@opoudjis how could we distinguish these contributors while creating BibTeX in the `to_bibtex` function?

**Comment by opoudjis** [comment]
If it's not too late:

````
institution => contributor[role/@type = "sponsor"]
````

should be:

````
institution => contributor[role/@type = "distributor" & role = "sponsor"]
````

The choice of institution, organization, or school in BibTeX is wholly determined by the bibliographic type of work: they are underlyingly the same organisation.

````
subtitle =>  title[@type ="main"]
````

That is an error, it should be `title[@type ="subtitle"]`

**Comment by andrew2net** [comment]
> institution => contributor[role/@type = "distributor" & role = "sponsor"]

@opoudjis what types `organization` and `school` should be?

**Comment by opoudjis** [comment]
> @opoudjis what types organization and school should be?

The same. The only difference betwen them is that institution occurs in `bibitem/@type = tech report`, organization in `bibitem/@type = inproceedings, conference, manual, proceedings`, and school in `bibitem/@type = mastersthesis, phdthesis`.
