### ISSUE TITLE
Remove any discrepancies between bibitem encodings that impact relaton

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton#39]
Because we cannot have multiple schemas parsing the same references in a document (#35), all Relaton XML output from all relaton gems must align with the same schema. If I have to, I will use goddamn `xs:any` to get them parsing.

With a backlog of 75 issues, I don't have the time to do the analysis of what the discrepancies are between different flavours of relaton. @andrew2net, I ask that you go through the Relaton gems and grammars, and tell me what those discrepancies are; they need to be  eliminated where at all possible. I will decide which ones can be eliminated, and make the appropriate requests back to you.

**Comment by opoudjis** [comment]
So bibdata can be distinct for different flavours, for reasons of presentation, but bibdata is reduced to a common bibitem representation, which is universal. And converting flavour-specific bibdata to generic bibitem will become functionality necessary to relaton-cli, once we know what that those discrepancies are.

**Comment by opoudjis** [comment]
@andrew I will do the analysis, because this needs to be done before anything else in the relaton stack. I've removed it from your to-do list. You will have plenty to do in followup anyway.

**Comment by opoudjis** [comment]
@andrew2net This is the beginning of me refactoring bibitem. This will break things. I think you should wait until I finish before programming anything more in the relaton suite; several elements are going to change position. I will list all position changes here.

**Comment by opoudjis** [comment]
Change `status` from `FormattedString` to `( stage, substage?, iteration? )`, which matches the modelling of ISO. There is no text child of `status`, it moves to `status/stage`.

**Comment by abunashir** [comment]
@opoudjis: Not at the moment, but keep me in the loop in case we need to update anything there, thanks!

**Comment by abunashir** [comment]
@opoudjis: Not at the moment, but keep me in the loop in case we need to update anything there, thanks!

**Comment by opoudjis** [comment]
It will definitely have impacts, but I will summarise the changes here, and let you know when they are finalised

**Comment by opoudjis** [comment]
All refactoring done in this ticket but for allparts, about which I will decide tomorrow whether it goes to bibitem or is only in bibdata. Although it is only relevant to GB and ISO, and part referencing is subsumed in bibitem into the identifier, I'm inclined to allow it in bibitem, since it is customised by language.

**Comment by opoudjis** [comment]
allparts modelled as `extent[@type = 'part']/referenceFrom = all`.

All discrepancies have been resolved.
