### ISSUE TITLE
bibdata vs bibitem return

### ISSUE THREAD

**Issue by opoudjis** [metanorma/relaton#40]
Now that the refactoring of the relaton grammar is finished, you will need to implement it.

Citations are expressed in the bibitem element of Relaton XML, which is BibliographicItem plus an `id` attribute passed in as an argument. This is what relaton has been returning until now with its fetch_std() method.

Metadata about a document is expressed in the bibdata element of Metanorma XML. This is a superset of BibliographicItem: it does not have the `id` attribute, and it has an additional `ext` element, containing metadata specific to the given flavour.

Ronald has been getting you to fill out more information in what the individual flavour gems return. It turns out this information mostly belongs to bibdata/ext.

You will need to create now two fetches, or a single fetch with two options. By default, wrap the XML in a bibitem container, as is currently the case, and do not include the ext element. The content of the bibitem element will come from relaton-bib.

If bibdata is selected, wrap the XML in a bibdata container, and add an ext element. The contents of the ext element will come from the individual flavour gems.

**Comment by andrew2net** [comment]
@opoudjis where is the attribute `id` passed from?

**Comment by opoudjis** [comment]
We've discussed this since: id should be generated internally and not passed in.
