### ISSUE TITLE
Do not crash when unable to connect to Internet

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/relaton#49]
This applies to the generic `relaton` gem interface. i.e. not at the `relaton-*` level.

1. If there is no cache, return an empty result. A user (such as Metanorma) needs to handle this possibility. 

2. If there is a cached entry, return the cached entry but indicate that it may be inaccurate.

Here's the trace for relaton-ietf:

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:981:in `connect'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:609:in `start'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/2.5.0/net/http.rb:485:in `get_response'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/relaton-ietf-0.5.5/lib/relaton_ietf/scrapper.rb:113:in `get_page'
```

**Comment by andrew2net** [comment]
When a request fails the relaton saves not_found in its cache https://github.com/metanorma/relaton-cli/issues/55#issuecomment-504447396
It needs to raise an error to avoid saving anything in cash and pass an error message to gems depended on the relaton.
But it should catch `OpenSSL::SSL::SSLError` and raise `RelatonBib::RequestError`. Seems `OpenSSL::SSL::SSLError` missed in catch. I'll fix it.
