### ISSUE TITLE
Creates files with trailing underscore.

### ISSUE THREAD

**Issue by andrew2net** [metanorma/relaton#52]
Moved from https://github.com/metanorma/relaton-iso/issues/58

In geolexica.org , both of these files are created in the cache:
- iso_12620_1999.xml
- iso_12620_1999_.xml

**Comment by ronaldtse** [comment]
@andrew2net it seems that the problem is Relaton thinks a cached entry doesn't exist but it already does. Does this fix that?

**Comment by andrew2net** [comment]
@ronaldtse this fix only trailing underscore in filenames.

**Comment by ronaldtse** [comment]
Got it, so the remaining task is #53.
